### ISSUE TITLE
Erro normalização de palavras estranhas

### ISSUE THREAD

**Issue by staticdev** [tfcbertaglia/enelvo#6]
Boa noite Thales.. com o uso mais intenso do seu normalizador, detectei um caso atípico em que você levanta um normalizador e ele gera uma exceção não tratada, para reproduzir utilize o código:

```
from enelvo.normaliser import Normaliser

norm = Normaliser(tokenizer='readable')
message = 'aosdfiosdmfaoi'
reply = norm.normalise(message)

```

Traceback:

```
09/01/2019 22:04:54 mensagem: aosdfiosdmfaoi
09/01/2019 22:04:54 192.168.208.13 - - [09/Jan/2019 22:04:54] "POST /reply HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/__init__.py", line 61, in reply
    reply = norm.normalise(message)
  File "/app/enelvo/normaliser.py", line 107, in normalise
    self.logger.error(
  AttributeError
```

Abraços

Thiago

**Comment by tfcbertaglia** [comment]
O normalizador realmente não consegue (e nem deveria) normalizar essa palavra. Na versão interativa dá erro do sistema mesmo (não do Python). 

Era um problema com o logger. Agora roda o código, mas a saída é a mesma palavra pois o sistema não encontra nenhum candidato.

**Comment by staticdev** [comment]
Perfeito Thales, valeu!
